apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: nodejs-health-check-oq1v
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: nodejs-health-check-oq1v
    app.kubernetes.io/part-of: e2e-nodejs
  name: nodejs-health-check-oq1v
spec:
  ports:
  - name: "3001"
    port: 3001
    targetPort: 3001
  selector:
    app.kubernetes.io/instance: nodejs-health-check-oq1v
status:
  loadBalancer: {}
